// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS1jOP6ZBgzIUflkEQbV_xK8zFaj12hrU',
    appId: '1:203931109748:web:99e1ad2cc1a09ab1424421',
    messagingSenderId: '203931109748',
    projectId: 'servicesrq-ba4b8',
    authDomain: 'servicesrq-ba4b8.firebaseapp.com',
    storageBucket: 'servicesrq-ba4b8.firebasestorage.app',
    measurementId: 'G-JC75V1DDY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL0ac7w8Rp43jnu4d_dtTBgozLkPDGHDM',
    appId: '1:203931109748:android:c5f9869f4bc6a26e424421',
    messagingSenderId: '203931109748',
    projectId: 'servicesrq-ba4b8',
    storageBucket: 'servicesrq-ba4b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKKPYwxrgw7rGnmYgdE7xvOnSUcjMkjiA',
    appId: '1:203931109748:ios:7d33907c2cc85fe7424421',
    messagingSenderId: '203931109748',
    projectId: 'servicesrq-ba4b8',
    storageBucket: 'servicesrq-ba4b8.firebasestorage.app',
    iosBundleId: 'com.visioncit.servicesrq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKKPYwxrgw7rGnmYgdE7xvOnSUcjMkjiA',
    appId: '1:203931109748:ios:7d33907c2cc85fe7424421',
    messagingSenderId: '203931109748',
    projectId: 'servicesrq-ba4b8',
    storageBucket: 'servicesrq-ba4b8.firebasestorage.app',
    iosBundleId: 'com.visioncit.servicesrq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS1jOP6ZBgzIUflkEQbV_xK8zFaj12hrU',
    appId: '1:203931109748:web:7851b9c5e1ec60c5424421',
    messagingSenderId: '203931109748',
    projectId: 'servicesrq-ba4b8',
    authDomain: 'servicesrq-ba4b8.firebaseapp.com',
    storageBucket: 'servicesrq-ba4b8.firebasestorage.app',
    measurementId: 'G-JL7D7ZE3D6',
  );
}
